name: Publish Package to npmjs
on:
    release:
        types: [published]
jobs:
    build:
        environment: deployment
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm version ${{ github.event.release.tag_name }}
            - run: npm ci
            - run: |
                  git config user.email "action@github.com"
                  git config user.name "GitHub Action"
                  git add package.json package-lock.json
                  git commit -m "Release version ${{ github.event.release.tag_name }}"
                  git push origin HEAD:master
            - run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
